create table accidents(
  date date,
  date_precision enum('day','month','quarter','year'),
  cause_of_accident enum('Shaving cut','Walking fall','Running fall','Traffic accident','Object drop','Minor cut with delayed bleeding','Non-injury bleeding','Insect bite'),
  physical_injury_details varchar(2000),
  physical_injury_severity int(11),
  other_damage_details varchar(2000),
  notes_doc varchar(200)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into accidents(date, date_precision, cause_of_accident, physical_injury_details, physical_injury_severity, other_damage_details, notes_doc) values
  ('2014-12-14','day','Running fall','A significant scrape of the knee; this prompted me to get my Tdap vaccine the same day. For a few days, I needed to sit with my knees spread out.',5,null,null),
  ('2019-09-10','day','Traffic accident','I fell on my right side and my injuries were mainly to my right arm and a little below the waist. I also had stiffness in a few parts of my body.',4,null,'https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2019/2019-09-10-traffic-accident.md'),
  ('2020-07-01','quarter','Object drop',null,null,'I dropped one of my glass food storage containers. I had placed it near the edge of the countertop due to the lack of space on the countertop near the sink (with stuff from my housemates having used up all the space), and it fell after a slight perturbation.',null),
  ('2022-04-05','day','Running fall','This was a relatively milder fall than my previous running fall; I scraped the side of my right knee as well as my right shoulder, and also got bruises on my left and right palm.',2,'I also cracked my phone screen that I had been holding in my left hand.','https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2022/2022-04-05-fall-and-phone-screen-crack.md'),
  ('2022-04-21','day','Object drop',null,null,'While putting stuff in and out of my vegetable tray in the refrigerator at my new place, I failed to realize that the capacity of this vegetable tray is smaller, so it dropped. Though a very small drop, it caused a crack in the tray (albeit not one that could be felt) and also a chipping in a door handle facing the tray.',null),
  ('2022-05-27','day','Shaving cut','While shaving, I got cuts in the cheek area just to the right of my nose, as well as in a few places under my jaw. None of the cuts were too serious; they clotted on their own without need of bandages and there was very little bleeding. Nonetheless, the existence of several simultaneous cuts suggests that there was some systematic issue such as insufficiently moist or soft skin, or a badly functioning razor blade. For the future, I''ll do more preparatory work with making my skin soft and moist prior to shaving.',0,null,'https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2022/2022-05-26-eye-and-skin-irritation.md'),
  ('2022-05-29','day','Non-injury bleeding','While running, I noticed red stains on my sweatshirt pocket; upon investigation I found that my left middle finger knuckle was bleeding. The bleeding did not seem related to any injury but was due to dry, cracked skin. I suspect it''s a side effect of increased skin irritation over the past few days.',0,'There were blood stains on my sweatshirt; they were mostly gone when I treated with soap and water and were fully gone after laundry the same day (I did pre-treat with a stain remover though that probably wasn''t needed).','https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2022/2022-05-26-eye-and-skin-irritation.md'),
  ('2022-07-01','day','Minor cut with delayed bleeding','A slight cut on my right middle finger PIP joint knuckle that had probably occurred a few days ago when my hand brushed against a zipper finally bled a little bit. I had been keeping the cut well-covered with vaseline for the previous few days, and this might have slowed down its progress to bleeding but wasn''t able to prevent it from getting to bleeding. I wrapped the cut in a bandage in the hope that this would make result in faster healing.',0,null,'https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2022/2022-07-01-bleeding-cut-on-right-middle-finger-pip-joint.md'),
  ('2024-06-03','day','Minor cut with delayed bleeding','I got a paper cut from the side of the folded sticker paper when reaching into the bag to take stuff out after arriving in Portland for my trip. The cut was at the tip of my middle finger (front/side area). Although it didn''t hurt much, its location at the tip of my finger made the initial bleeding very inconvenient. I bandaged it for about 1.5 hours which was enough for it to stop bleeding and heal, and allowed me to continue unpacking and typing on my computer. I was able to remove the bandage and proceed normally after that time, with no need to adjust my subsequent activities. I have updated my cautionary notes around travel to mention this.',0,null,null),
  ('2024-06-08','day','Minor cut with delayed bleeding','This was a case of a paper cut against the residue of a paper cover on a vegan probiotic yogurt bottle when rinsing it after use. Bleeding was brief but nontrivial; I had to use bandages a few times including one overnight.',1,null,'https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-06-08-paper-cut-from-yogurt-cover.md'),
  ('2024-07-21','day','Minor cut with delayed bleeding','The source of the cut is unclear. It cut the right middle finger around the PIP area back side. See https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-07-21-finger-injuries.md for more information.',0,null,'https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-07-21-finger-injuries.md'),
  ('2024-07-21','day','Minor cut with delayed bleeding','I got this very slight cut on my thumb when opening a bandage pack trying to see if the bigger bandages might be suitable for the right middle finger cut. See https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-07-21-finger-injuries.md for more information.',0,null,'https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-07-21-finger-injuries.md'),
  ('2025-01-18','day','Minor cut with delayed bleeding','I stubbed my right little toe against the chair. See https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2025/2025-01-18-right-little-toe-stub.md for more information.',0,null,'https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2025/2025-01-18-right-little-toe-stub.md'),
  ('2025-07-08','day','Insect bite','When walking outdoors, I got stung by a bee-like insect (probably a wasp). https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2025/2025-07-08-insect-bite.md for more information.',1,null,'https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2025/2025-07-08-insect-bite.md');
