create table food_types(
  `short_name` varchar(200) primary key not null,
  `long_name` varchar(200),
  `url` varchar(200),
  `calories` decimal(13,2),
  `broad_food_type` varchar(200),
  /* fat-related columns */
  `total_fat_in_grams` decimal(13,2),
  `saturated_fat_in_grams` decimal(13,2),
  `trans_fat_in_grams` decimal(13,2),
  `monounsaturated_fat_in_grams` decimal(13,2),
  `polyunsaturated_fat_in_grams` decimal(13,2),
  /* cholesterol */
  `cholesterol_in_mg` decimal(13,2),
  /* sodium and potassium (mostly from salts) */
  `sodium_in_mg` decimal(13,2),
  `potassium_in_mg` decimal(13,2),
  /* carbohydrate-related columns */
  `total_carb_in_grams` decimal(13,2),
  `fiber_in_grams` decimal(13,2),
  `sugars_in_grams` decimal(13,2),
  /* protein-related columns */
  `protein_in_grams` decimal(13,2),
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */
  `vitamin_a_in_mcg` decimal(13,2),
  `vitamin_c_in_mg` decimal(13,2),
  `vitamin_d_in_mcg` decimal(13,2),
  `calcium_in_mg` decimal(13,2),
  `iron_in_mg` decimal(13,2),
  /* columns for other less commonly reported vitamins and minerals */
  `vitamin_b6_in_mg` decimal(13,2),
  `vitamin_b12_in_mcg` decimal(13,2),
  `vitamin_e_in_mg` decimal(13,2),
  `vitamin_k_in_mcg` decimal(13,2),
  `magnesium_in_mg` decimal(13,2),
  `phosphorus_in_mg` decimal(13,2),
  `zinc_in_mg` decimal(13,2),
  `copper_in_mg` decimal(13,2),
  `oxalate_in_mg` decimal(13,2),
  /* notes column */
  `notes` varchar(2000),
  constraint broad_food_type_exists foreign key (broad_food_type) references broad_food_types (broad_food_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into food_types(short_name, long_name, url, calories,
  /* broad food types */ broad_food_type,
  /* fat-related columns */ total_fat_in_grams, saturated_fat_in_grams, trans_fat_in_grams, monounsaturated_fat_in_grams, polyunsaturated_fat_in_grams,
  /* cholesterol */ cholesterol_in_mg,
  /* sodium and potassium (mostly from salts) */ sodium_in_mg, potassium_in_mg,
  /* carbohydrate-related columns */ total_carb_in_grams, fiber_in_grams, sugars_in_grams,
  /* protein-related columns */ protein_in_grams,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ vitamin_a_in_mcg, vitamin_c_in_mg, vitamin_d_in_mcg, calcium_in_mg, iron_in_mg,
  /* columns for other less commonly reported vitamins and minerals */ vitamin_b6_in_mg, vitamin_b12_in_mcg, vitamin_e_in_mg, vitamin_k_in_mcg, magnesium_in_mg, zinc_in_mg, phosphorus_in_mg, copper_in_mg,
  /* special oxalate column added in light of risk of kidney stones */ oxalate_in_mg,
  /* notes column */ notes) values

  ('TJ Sauerkraut','Raw & Fermented Trader Joe''s Sauerkraut with Pickled Persian Cucumbers','https://www.traderjoes.com/fearless-flyer/article/5455',85,
  /* broad food type */ 'Sauerkraut',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 3400,0,
  /* carbohydrate-related columns */ 34,17,17,
  /* protein-related columns */ 0,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 0,225,0,0,0,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The nutrition data is extrapolated from the data for the serving size (30g) by scaling up to the total mass (510g). I generally eat this mixed with almond milk across several meals. For Vitamin C, the amount was specified as 15% of daily value for 1 serving; I assumed a daily value of 90 mg for calculations.'),

  ('TJ Almond Milk','Trader Joe'' Almond Beverage Original Unsweetened','http://www.whatsgoodattraderjoes.com/2014/02/trader-joes-non-dairy-almond-beverage.html',236,
  /* broad food type */ 'Almond milk',
  /* fat-related columns */ 20,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 1260,275,
  /* carbohydrate-related columns */ 8,8,8,
  /* protein-related columns */ 8,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 708,0,39,3071,3,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The nutrition data is extrapolated from tthe data for the serving size (240ml) by scaling up to the total volume (1.89L), leading to a scaling factor of 7.875. For Vitamin A and calcium, values per serving were specified as a percentage of daily value, rather than in absolute terms. I used the following daily values to get absolute numbers: 800 mcg for Vitamin A, and 1,000 mg for calcium. Note that the data shown in the link is a bit outdated; in particular, the calories are now lower (30 per serving instead of 40).'),

  ('TJ Whole Wheat Wraps','Trader Joe''s Organic Olive Oil Whole Wheat Wraps','https://www.fooducate.com/product/Trader-Joe-s-Whole-Wheat-Wraps-Olive-Oil/D7FB0082-5D10-11E0-A55F-1231380C180E',1020,
  /* broad food type */ 'Whole wheat tortilla',
  /* fat-related columns */ 30,3,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 2760,300,
  /* carbohydrate-related columns */ 192,18,0,
  /* protein-related columns */ 36,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 0,0,0,660,8,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The dietary information in the link seems a little outdated compared to what I see on the actual item. There are 6 wraps and the information in both places is per wrap, so I am multiplying by 6.'),

  ('TJ Whole Wheat Tortillas','Trader Joe''s Organic Extra Virgin Olive Oil Tortillas',NULL,1140,
  /* broad food type */ 'Whole wheat tortilla',
  /* fat-related columns */ 18,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 2100,540,
  /* carbohydrate-related columns */ 192,12,0,
  /* protein-related columns */ 30,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 0,0,0,1020,2.4,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'There are 6 tortillas per container and the information is per tortilla, so I am multiplying by 6.'),

  ('TJ Misal Curry','Trader Joe''s Misal Curry with Brown Rice: Sprouted Beans in a Spicy Curry Sauce','http://www.whatsgoodattraderjoes.com/2021/01/trader-joes-misal-curry.html',420,
  /* broad food type */ NULL,
  /* fat-related columns */ 17,8,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 970,350,
  /* carbohydrate-related columns */ 44,15,0,
  /* protein-related columns */ 23,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 0,0,0,40,0,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */'The dietary information in the link matches what I see on the actual item, but the link cuts off the information on vitamin D, calcium, iron, and potassium. Since the serving size used is the entire package, we did not need to use a multiplier.'),

  ('TJ Veg Biryani','Trader Joe''s Vegetable Biryani with Vegetable Dumplings','http://www.whatsgoodattraderjoes.com/2014/07/trader-joes-vegetable-biryani.html',420,
  /* broad food type */ NULL,
  /* fat-related columns */ 12,2,0,NULL,NULL,
  /* cholesterol */ 5,
  /* sodium and potassium (mostly from salts) */ 1370,480,
  /* carbohydrate-related columns */ 72,12,5,
  /* protein-related columns */ 10,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 0,0,0,60,2,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The dietary information in the link is somewhat outdated. I used the information from an actual item. The information there includes a column for total value per container; I used that instead of using the column for value per serving size and multiplying.'),

  ('TJ Baby Spinach','Trader Joe''s Les Salades du Midi Baby Spinach 12 oz','https://www.fooducate.com/product/Trader-Joe-s-Baby-Spinach/35B7FA44-169F-11E0-BF92-FEFD45A4D471',80,
  /* broad food type */ 'Spinach',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 260,1896,
  /* carbohydrate-related columns */ 12,8,0,
  /* protein-related columns */ 8,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 1600,96,0,320,8,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ 1929, /* I used 567 mg per 100 grams from https://ohf.org/vegetables-oxalate/ */
  /* notes */ 'I used information printed on the back of an actual item. The information was specified in per-serving terms, with 4 servings per container, so I multiplied the values by 4 for reporting.'),

  ('TJ Baby Spinach 6 oz','Trader Joe''s Organic Baby Spinach 6 oz','https://www.myfooddiary.com/foods/7239846/trader-joes-organic-baby-spinach',40,
  /* broad food type */ 'Spinach',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 130,940,
  /* carbohydrate-related columns */ 6,4,0,
  /* protein-related columns */ 4,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 800,48,0,160,4.6,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ 964, /* I used 567 mg per 100 grams from https://ohf.org/vegetables-oxalate/ */
  /* notes */ 'The data given uses a serving size of 85 grams, half the size of the packet, so I multiplied all numbers by 2. Overall this is very similar to the full-sized non-organic baby spinach, just scaled down by 2, with the slight differences likely reflecting rounding errors rather than genuine differences.'),

  ('Trader Giotto''s Olive Oil','Trader Giotto''s Extra Virgin Olive Oil',NULL,8000,
  /* broad food type */ 'Olive oil',
  /* fat-related columns */ 933,133,0,667,100,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 0,0,
  /* carbohydrate-related columns */ 0,0,0,
  /* protein-related columns */ 0,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 0,0,0,0,0,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'Nutritional information was provided per serving, with a serving size of 15 mL compared to container size of 1000 mL. All amounts provided were scaled appropriatey to container size.'),

  ('Trader Jose''s 250ml Garlic Olive Oil','Trader Joe''s Spanish Organic Extra Virgin Garlic Flavored Olive Oil 250 ml',NULL,2167,
  /* broad food type */ 'Olive oil',
  /* fat-related columns */ 250,33,0,183,25,
  /* cholesterol */ NULL,
  /* sodium and potassium (mostly from salts) */ 0,0,
  /* carbohydrate-related columns */ 0,0,0,
  /* protein-related columns */ 0,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,NULL,NULL,NULL,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'Nutritional information was provided per serving, with a serving size of 15 mL compared to container size of 250 mL. All amounts provided were scaled appropriately to container size.'),

  ('Trader Giotto''s 500ml Olive Oil','Trader Giotto''s 100% Italian Organic Extra Virgin Olive Oil 500 ml',NULL,4000,
  /* broad food type */ 'Olive oil',
  /* fat-related columns */ 467,67,0,333,50,
  /* cholesterol */ NULL,
  /* sodium and potassium (mostly from salts) */ 0,0,
  /* carbohydrate-related columns */ 0,0,0,
  /* protein-related columns */ 0,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,NULL,NULL,NULL,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'Nutritional information was provided per serving, with a serving size of 15 mL compared to container size of 500 mL. All amounts provided were scaled appropriately to container size.'),

  ('TJ Sea Salt','Trader Joe''s Sea Salt: Fine Crystals','https://www.amazon.com/Trader-Joes-Salt-Fine-Crystals/dp/B00IGY6P6K',0,
  /* broad food type */ 'Table salt',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 275000,0,
  /* carbohydrate-related columns */ 0,0,0,
  /* protein-related columns */ 0,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 0,0,0,0,0,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The nutrition information provided says that one serving of 1.2 g contains 440 mg of sodium; there are 625 servings in a 750 g container so multiplying by 625 gives 275000 mg = 275 g. This is in the ballpark of what you would expect based on the proportion by mass of sodium in the NaCl molecule.'),

  ('Morton Iodized Sea Salt','Morton Iodized Sea Salt 26 oz','https://www.kroger.com/p/morton-iodized-sea-salt/0002460001088',0,
  /* broad food type */ 'Table salt',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 289300,0,
  /* carbohydrate-related columns */ 0,0,0,
  /* protein-related columns */ 0,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 0,0,0,0,0,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The nutrition information provided says that one serving of 1.4 g contains 550 mg of sodium; there are 526 servings in a 737 g container so multiplying by 526 gives 289300 mg = 289.3 g. This is in the ballpark of what you would expect based on the proportion by mass of sodium in the NaCl molecule.'),

  ('Morton Iodized Salt','Morton Iodized Table Salt 26 oz','https://www.kroger.com/p/morton-iodized-table-salt/0002460001003',0,
  /* broad food type */ 'Table salt',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 289690,0,
  /* carbohydrate-related columns */ 0,0,0,
  /* protein-related columns */ 0,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 0,0,0,0,0,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The nutrition information provided says that one serving of 1.5 g contains 590 mg of sodium; there are 491 servings in a 737 g container so multiplying by 491 gives 289690 mg = 289.69 g. This is in the ballpark of what you would expect based on the proportion by mass of sodium in the NaCl molecule.'),

  ('TJ Carrots','Trader Joe''s Cut and Peeled Carrots','https://www.fooducate.com/product/Trader-Joe-s-Cut-and-Peeled-Carrots/2FC11530-43D1-11E0-A55F-1231380C180E',35,
  /* broad food type */ 'Carrot',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 65,270,
  /* carbohydrate-related columns */ 8,3,5,
  /* protein-related columns */ 1,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 1800,6,0,20,0.36,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The website did not specify number of servings per container, so I assumed it is 1 (that is consistent with the size as I remember it).'),

  ('Beefsteak tomato','Trader Joe''s beefsteak tomato','https://www.nutritionix.com/food/beefsteak-tomato',25,
  /* broad food type */ 'Tomato',
  /* fat-related columns */ 0.4,0.1,0,0.1,0.1,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 9.1,431,
  /* carbohydrate-related columns */ 7.1,2.2,4.8,
  /* protein-related columns */ 1.6,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 270,38,0,14,0.216,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The actual size of beefsteak tomatoes I consume varies and may not match the specification on Nutritionix.'),

  ('Eggplant','Trader Joe''s eggplant','https://www.eatthismuch.com/food/nutrition/eggplant,1975/',137,
  /* broad food type */ 'Eggplant',
  /* fat-related columns */ 1,0.2,0,0.1,0.4,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 11,1254.9,
  /* carbohydrate-related columns */ 32.2,16.4,19.3,
  /* protein-related columns */ 5.4,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 5.5,12.1,0,49.3,1.3,
  /* columns for other less commonly reported vitamins and minerals */ 0.5,0,1.6,19.2,76.7,131.5,0.9,0.4,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The data as shown on this website may differ from actual data for the bell peppers. Other information is on the site.'),

  ('Red bell pepper','Trader Joe''s red bell pepper','https://www.eatthismuch.com/food/nutrition/red-bell-pepper,2440/',36.9,
  /* broad food type */ 'Bell pepper',
  /* fat-related columns */ 0.4,0,0,0,0.1,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 4.8,251.1,
  /* carbohydrate-related columns */ 7.2,2.5,5,
  /* protein-related columns */ 1.2,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 186.8,152,0,8.3,0.5,
  /* columns for other less commonly reported vitamins and minerals */ 0.3,0,1.9,5.8,14.3,30.9,0.3,0,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The data as shown on this website may differ from actual data for the bell peppers. Other information: Manganese: 0.1 mg, Selenium: 0.1 mcg, Thiamine: 0.1 mg, Riboflavin: 0.1 mg, Niacin: 1.2 mg, Folate: 54.7 mcg, Choline: 6.7 mg.'),

  ('Orange bell pepper','Trader Joe''s orange bell pepper','https://www.nutritionix.com/food/orange-bell-pepper',32,
  /* broad food type */ 'Bell pepper',
  /* fat-related columns */ 0.2,0,0,0,0.1,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 2.3,189.2,
  /* carbohydrate-related columns */ 7.6,1.4,5,
  /* protein-related columns */ 1,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 630 /* from https://www.eatthismuch.com/food/nutrition/orange-bell-pepper,1534951/ */,146.7 /* from https://www.eatthismuch.com/food/nutrition/orange-bell-pepper,1534951/ */,0,10,0.5,
  /* columns for other less commonly reported vitamins and minerals (from https://www.eatthismuch.com/food/nutrition/orange-bell-pepper,1534951/ as nutritionix doesn't have the info) */ 0,0,0,0,0,0,0,0,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'I used https://www.eatthismuch.com/food/nutrition/orange-bell-pepper,1534951/ for some of the data for vitamins and minerals, as the primary source https://www.nutritionix.com/food/orange-bell-pepper doesn''t have this data.'),

  ('Yellow bell pepper','Trader Joe''s yellow bell pepper','https://www.nutritionix.com/i/usda/yellow-pepper-1-medium/5775254ba95125266c766bb3',32,
  /* broad food type */ 'Bell pepper',
  /* fat-related columns */ 0.3,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 2.4,252.3,
  /* carbohydrate-related columns */ 7.5,1.1,0,
  /* protein-related columns */ 1.2,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 18.6 /* from https://www.eatthismuch.com/food/nutrition/yellow-peppers,2560/ */,341.3 /* from https://www.eatthismuch.com/food/nutrition/yellow-peppers,2560/ */,0,20.5 /* from https://www.eatthismuch.com/food/nutrition/yellow-peppers,2560/ */,0.9 /* from https://www.eatthismuch.com/food/nutrition/yellow-peppers,2560/ */,
  /* columns for other less commonly reported vitamins and minerals */ 0.3,0,NULL,NULL,22.3,0.3,44.6,0.2,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'I used https://www.nutritionix.com/i/usda/yellow-pepper-1-medium/5775254ba95125266c766bb3 for some of the data and https://www.eatthismuch.com/food/nutrition/yellow-peppers,2560/ for the rest. The results vary between medium and large pepper, so there is some discrepancy to be addressed.'),

  ('Green bell pepper','Trader Joe''s green bell pepper','https://www.eatthismuch.com/food/nutrition/green-bell-pepper,2080/',23.8,
  /* broad food type */ 'Bell pepper',
  /* fat-related columns */ 0.2,0.1,0,0,0.1,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 3.6,208.3,
  /* carbohydrate-related columns */ 5.5,2,2.9,
  /* protein-related columns */ 1,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 21.4,95.7,0,11.9,0.4,
  /* columns for other less commonly reported vitamins and minerals */ 0.3,0,0.4,8.8,11.9,23.8,0.2,0.1,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The data as shown on this website may differ from actual data for the bell peppers. Other information is on the site.'),

  ('TJ Walnuts','Trader Joe''s Organic Raw Walnuts: Halves & Pieces',NULL,2186,
  /* broad food type */ 'Walnut',
  /* fat-related columns */ 218.6,18.2,0,157.9,30.4,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 0,1457,
  /* protein-related columns */ 48.6,
  /* carbohydrate-related columns */ 48.6,24.3,0,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,36.4,9.7,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'Data was provided for a serving size of 28g, and the container size was 340g. All amounts have been scaled appropriately.'),

  ('TJ Madras Lentils','Trader Joe''s Indian Fare Madras Lentils',NULL,300,
  /* broad food type */ NULL,
  /* fat-related columns */ 13,6,0,NULL,NULL,
  /* cholesterol */ 25,
  /* sodium and potassium (mostly from salts) */ 1040,720,
  /* carbohydrate-related columns */ 35,10,3,
  /* protein-related columns */ 13,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0.3,90,4.3,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'Data was provided for the full containe (280 g) that is said to be two servings (140 g each).'),

  ('Alvarado Sprouted Wheat Tortillas','Alvarado St. Bakery Freshly Sprouted Wheat Burrito Size Tortillas',NULL,1020,
  /* broad food type */ 'Whole wheat tortilla',
  /* fat-related columns */ 15,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 1920,870,
  /* carbohydrate-related columns */ 180,30,6,
  /* protein-related columns */ 42,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,90,6,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes column */ 'Data was provided for a serving size of 1 tortilla (62 g) and the container had 6 tortillas. Therefore all numbers were multiplied by 6.'),

  ('TJ English Shelled Peas','Trader Joe''s English Shelled Peas','http://exploringtraderjoes.blogspot.com/2015/01/trader-joes-english-peas.html',240,
  /* broad food type */ 'Pea',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 15,690,
  /* carbohydrate-related columns */ 42,15,15,
  /* protein-related columns */ 15,
  /* columns for commonly reported vitamins and minerals */ 405,162,0,60,2,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes column */ 'Data was provided for a serving size of 96g (2/3 cup). There are 3 servings in a container. Therefore all numbers were multiplied by 3.'),

  ('TJ Miso Ginger Broth','Trader Joe''s Miso Ginger Broth 32 Oz','https://www.amazon.com/Trader-Joes-Miso-Ginger-Broth/dp/B00FO9RRXK',60,
  /* broad food type */ NULL,
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 2600,NULL,
  /* carbohydrate-related columns */ 8,0,0,
  /* protein-related columns */ 4,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 0,0,0,0,0,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes column */ 'Data was provided for a serving size of 240g. There are 4 servings in a container. Therefore all numbers were multiplied by 4.'),

  ('TJ White Miso Paste','Trader Joe''s White Miso Paste','https://www.whatsgoodattraderjoes.com/2023/02/trader-joes-white-miso-paste.html',250,
  /* broad food type */ NULL,
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ NULL,
  /* sodium and potassium (mostly from salts) */ 4250,NULL,
  /* carbohydrate-related columns */ 50,NULL,NULL,
  /* protein-related columns */ 12.5 /* it says "less than 1 gram so I took 0.5 grams per serving */,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,NULL,NULL,NULL,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'Data was provided for a serving size of 6 grams; there are 25 servings in a container so all values were multiplied by 25.'),

  ('TJ Organic Tomato and Roasted Red Pepper Soup','Trader Joe''s Organic Tomato & Roasted Red Pepper Soup','https://www.amazon.com/Trader-Joes-Organic-Tomato-Roasted/dp/B00B4K8QTW',400,
  /* broad food type */ NULL,
  /* fat-related columns */ 8,6,0,0,0,
  /* cholesterol */ 40,
  /* sodium and potassium (mostly from salts) */ 3000,2000,
  /* carbohydrate-related columns */ 64,4,40,
  /* protein-related columns */ 20,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 360,14.4,0,600,0.64,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes column */ 'Data was provided for a serving size of 240 mL. There are 4 servings in a container. Therefore all numbers were multiplied by 4.'),

  ('TJ Beans','Trader Joe''s Trimmed & Cleaned Green Beans','https://www.carbmanager.com/food-detail/md:eadc9717e5e9c4ce7062c1260532c563/trimmed-cleaned-green-beans',25,
  /* broad food type */ 'Bean',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 5,NULL,
  /* carbohydrate-related columns */ 6,3,3,
  /* protein-related columns */ 2,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 150,15,0,40,0.7,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'Data was provided for the whole packet, that has a weight of 85 grams.'),

  ('TJ Broccoli Florets 12 oz','Trader Joe''s Broccoli Florets 12 oz','https://world.openfoodfacts.org/product/00317740/broccoli-florets-trader-joe-s',100,
  /* broad food type */ 'Broccoli',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 100,1104,
  /* carbohydrte-related columns */ 16,8,4,
  /* protein-related columns */ 12,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,164,4,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes column */ 'Data was provided for 85 grams, which is 1/4 of a packet.'),

  ('Dutch yellow potatoes 1.5 lb','Dutch yellow potatoes 1.5lb (~15 potatoes)','https://www.nutritionix.com/i/melissas/baby-dutch-yellow-potatoes/541055571c634b9a52447fca',480,
  /* broad food type */ 'Potato',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 108,2760,
  /* carbohydrate-related columns */ 108,18,6,
  /* protein-related columns */ 12,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,60,6,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ 333, /* I used 49 mg per 100 grams (the highest of related estimates) per https://ohf.org/vegetables-oxalate/ */
  /* notes */ 'I adjusted the setting for number of potatoes to 18 (from the default of 3), so as to match the expected weight of 1.5lb.'),

  ('Gold potatoes 3 lb','Gold potatoes 3 lb (~9 potatoes)','https://www.heb.com/product-detail/fresh-gold-potatoes/591301',990,
  /* broad food type */ 'Potato',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 0,5580,
  /* carbohydrate-related columns */ 234,18,9,
  /* protein-related columns */ 27,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,243,0,180,9.9,
  /* columns for other less commonly reported vitamins and minerals */ 1.8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ 666, /* I used 49 mg per 100 grams (the highest of related estimates) per https://ohf.org/vegetables-oxalate/ */
  /* notes */ 'The linked page isn''t for the brand I buy, but I expect the nutritional content to be similar. It gives the data per potato (148 grams, or about 1/3 of a lb), and there are approximately 9 potatoes in 3 lb. So I multiplied their numbers by 9.'),

  ('Russet potatoes 3 lb','Russet potatoes 3 lb (~9 potatoes)',NULL,990,
  /* broad food type */ 'Potato',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 0,5580,
  /* carbohydrate-related columns */ 234,18,9,
  /* protein-related columns */ 27,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,243,0,180,9.9,
  /* columns for other less commonly reported vitamins and minerals */ 1.8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ 666, /* I used 49 mg per 100 grams (the highest of related estimates) per https://ohf.org/vegetables-oxalate/ */
  /* notes */ 'I am being lazy and copying over the information for gold potatoes of a similar size, even though there are slight differences. The justification for this laziness is that I rarely get russet potatoes and using the value for gold potatoes for those rare occasions would still be better than putting nothing.'),

  ('Gold potatoes 5 lb','Gold potatoes 5 lb (~15 potatoes)','https://www.heb.com/product-detail/fresh-gold-potatoes/591301',1650,
  /* broad food type */ 'Potato',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 0,9300,
  /* carbohydrate-related columns */ 390,30,15,
  /* protein-related columns */ 45,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,405,0,300,16.5,
  /* columns for other less commonly reported vitamins and minerals */ 3.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ 1111, /* I used 49 mg per 100 grams (the highest of related estimates) per https://ohf.org/vegetables-oxalate/ */
  /* notes */ 'The linked page isn''t for the brand I buy, but I expect the nutritional content to be similar. It gives the data per potato (148 grams, or about 1/3 of a lb), and there are approximately 15 potatoes in 5 lb. So I multiplied their numbers by 15.'),

  ('TJ Indian Style Flatbread','Trader Joe''s Traditional Indian Style Flatbread','https://www.aldireviewer.com/trader-joes-traditional-indian-style-flatbread/',1400,
  /* broad food type */ 'Non-whole wheat tortilla',
  /* fat-related columns */ 20,2,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 3120,360,
  /* carbohydrate-related columns */ 256,12,8,
  /* protein-related columns */ 44,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,4,760,16,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The data on the page is for 128 grams. I used a quantity of 4 to get the data for one pack. The actual number of pieces is 6, but their weight is less than 128 grams. The reason for the serving size used is not clear. https://www.carbmanager.com/food-detail/md:560fc054a24643bed7780727d8d5252c/indian-style-flatbread shows similar results.'),

  ('TJ Carb Savvy Tortillas','Trader Joe''s Carb Savvy Tortillas','https://www.facebook.com/itsfromtraderjoes/posts/pfbid0211r4kRZxWrdGwrLxyg2QsbRaa47ueBLNvCEpormKA4sYk8VgDLCitxZ5sPUmAEiel',450,
  /* broad food type */ 'Whole wheat tortilla',
  /* fat-related columns */ 15,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 1400,300,
  /* carbohydrate-related columns */ 90,60,50,
  /* protein-related columns */ 40,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,100,9,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The serving size is 1 tortilla, and there are 10 per container, so I multiplied by 10.'),

  ('Kite Hill Unsweetened Plain Almond Milk Yogurt','Kite Hill Unsweetened Plain Almond Milk Yogurt','https://www.amazon.com/Kite-Hill-Yogurt-Unsweetened-16/dp/B073QLS4SB',350,
  /* broad food type */ 'Vegan probiotic yogurt',
  /* fat-related columns */ 25,2.5,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 25,NULL,
  /* carbohydrate-related columns */ 22.5,7.5,2.5,
  /* protein-related columns */ 10,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,NULL,145,2.5,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The serving size used is 140 grams, with 2.5 servings per container. All values were therefore multiplied by 2.5.'),

  ('Kite Hill Greek Style Plant-Based Yogurt','Kite Hill Greek Style Plant-Based Yogurt','https://www.amazon.com/Kite-Hill-Plain-Unsweetened-Yogurt/dp/B09KTCNZMT',360,
  /* broad food type */ 'Vegan probiotic yogurt',
  /* fat-related columns */ 16,1.5,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 430,568,
  /* carbohydrate-related columns */ 12,3,1,
  /* protein-related columns */ 46,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,149,8,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'I directly used the values for the whole container printed on the physical container.'),

  ('Cocojune Organic Pure Coconut Dairy Free Yogurt','Cocojune Organic Pure Coconut Dairy Free Yogurt 16 oz','https://www.cocojune.co/products/pure-coconut/',760,
  /* broad food type */ 'Vegan probiotic yogurt',
  /* fat-related columns */ 72,60,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 40,600,
  /* carbohydrate-related columns */ 24,8,8,
  /* protein-related columns */ 8,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,NULL,40,2.24,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The serving size used is 4 oz, with 4 servings per container. All values were therefore multiplied by 4. For potassium the amount was given as 5% of RDA per serving; I used a RDA of 3000 for the calculation (this is the average between men and women). For calcium the amount was given as 1% of RDA per serving; I used an RDA of 1000 mg. For iron, the amount was given a s 7% of RDA per serving; I used an RDA of 8 mg.'),

  ('Lundberg Organic California White Basmati Rice','Lundberg Organic California White Basmati Rice 32 oz','https://www.amazon.com/Lundberg-Organic-California-White-Basmati/dp/B004WCND9C',3200,
  /* broad food type */ 'White rice',
  /* fat-related columns */ 10,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 0,1000,
  /* carbohydrate-related columns */ 720,0,0,
  /* protein-related columns */ 60,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,260,0,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The serving size used is 45 grams, 1/20 of the size of the container (907 grams). All amounts were scaled up by 20.'),

  ('Lundberg Sustainable California White Basmati Rice','Lundberg Sustainable California White Basmati Rice 32 oz','https://www.amazon.com/Lundberg-Family-Farms-White-Basmati/dp/B000QV32C6',3200,
  /* broad food type */ 'White rice',
  /* fat-related columns */ 10,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 0,1000,
  /* carbohydrate-related columns */ 720,0,0,
  /* protein-related columns */ 60,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,260,0,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The serving size used is 45 grams, 1/20 of the size of the container (907 grams). All amounts were scaled up by 20.'),

  ('Lundberg Organic California White Jasmine Rice','Lundberg Organic California White Jasmine Rice 32 oz','https://www.amazon.com/Lundberg-Family-Organic-California-Jasmine/dp/B077NHDPRC',3200,
  /* broad food type */ 'White rice',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 0,800,
  /* carbohydrate-related columns */ 720,20,0,
  /* protein-related columns */ 60,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,260,0,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The serving size used is 45 grams, 1/20 of the size of the container (907 grams). All amounts were scaled up by 20.'),

  ('Lundberg Sustainable California White Jasmine Rice','Lundberg Sustainable California White Jasmine Rice 32 oz','https://www.lundberg.com/products/white-jasmine-rice',3200,
  /* broad food type */ 'White rice',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 0,700,
  /* carbohydrate-related columns */ 720,20,0,
  /* protein-related columns */ 60,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,260,0,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The serving size used is 45 grams, 1/20 of the size of the container (907 grams). All amounts were scaled up by 20.'),

  ('Health Factory Zero Maida Bread','Health Factory Zero Maida Bread - (Simply Whole Wheat) 250g','https://www.thehealthfactory.in/products/zero-maida-simply-whole-wheat',613.05,
  /* broad food type */ 'Wheat bread',
  /* fat-related columns */ 3.25,0.85,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ NULL,NULL,
  /* carbohydrate-related columns */ 111.65,15.85,10.55,
  /* protein-related columns */ 34.3,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,NULL,NULL,NULL,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The serving size used is 100 grams, whereas the container size is 250 grams. All amounts were scaled by 2.5.'),

  ('Urban Platter Sauerkraut','Urban Platter Sauerkraut Original Pickled Probiotic Cabbage with Beetroot, 450g / 15.8oz [Raw, Organic & Powered by Bombucha]','https://www.amazon.in/Urban-Platter-Sauerkraut-Original-Probiotic/dp/B07NQB9KKL',286.1,
  /* broad food type */ 'Sauerkraut',
  /* fat-related columns */ 11.64,NULL,NULL,NULL,NULL,
  /* cholesterol */ NULL,
  /* sodium and potassium (mostly from salts) */ 4287.6,NULL,
  /* carbohydrate-related columns */ 37.27,NULL,NULL,
  /* protein-related columns */ 8.02,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,NULL,NULL,NULL,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The serving size used is 100 grams, whereas the container size is 710 grams. All amounts were scaled by 7.1.'),

  ('Wild Harvest Organic Lentils','Wild Harvest Organic Lentil','https://www.mywildharvest.com/our-products/product.organic-lentils-711535505730.html',1300,
  /* broad food type */ 'Lentils',
  /* fat-related columns */ 6.5,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 130,NULL,
  /* carbohydrate-related columns */ 299,91,0,
  /* protein-related columns */ 104,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,NULL,0,15.6,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The serving size used is 35 grams, with "about" 13 servings per container.'),

  ('TJ Green Lentils','Trader Joe''s Whole Green Lentils',NULL,1255,
  /* broad food type */ 'Lentils',
  /* fat-related columns */ 9.66,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 145,3381,
  /* carbohydrate-related columns */ 290,96.6,0.97,
  /* protein-related columns */ 96.6,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,96.6,30.9,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The serving size used is 47 grams, and the container size is 454 grams, so all amounts were scaled by 454/47.'),

  ('TJ Whole Wheat Lavash','Trader Joe''s Whole Wheat Lavash Bread',NULL,960,
  /* broad food type */ 'Whole wheat tortilla',
  /* fat-related columns */ 6,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 1200,1020,
  /* carbohydrate-related columns */ 192,36,0,
  /* protein-related columns */ 60,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 0,0,0,120,9.6,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The information at https://www.fooducate.com/product/Trader-Joe-s-Whole-Wheat-Lavash-Flatbread/5650DF8C-861A-DE3F-4F78-A6CD3099DD3A is somewhat outdated.'),

  ('TJ Mixed Baby Kale','Trader Joe''s Organic Mixed Baby Kale 5 oz',NULL,83.52,
  /* broad food type */ 'Kale',
  /* fat-related columns */ 1.67,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 50,701.6,
  /* carbohydrate-related columns */ 11.69,5,3.34,
  /* protein-related columns */ 6.68,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,0,217,2,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */14.2, /* using https://ohf.org/vegetables-oxalate/ that gives 10 mg per 100 g, scaled up to 142 g which is the container size*/
  /* notes */ 'The serving size is 85 g; the container size is 142 g, so the data had to be scaled by a factor of 142/85.'),

  ('TJ Kale','Trader Joe''s Kale 10 oz',NULL,135.7,
  /* broad food type */ 'Kale',
  /* fat-related columns */ 3.39,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 102,1425,
  /* carbohydrate-related columns */ 23.75,10.17,6.79,
  /* protein-related columns */ 13.57,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ 1425,346,0,441,4.07,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */28.4, /* using https://ohf.org/vegetables-oxalate/ that gives 10 mg per 100 g, scaled up to 142 g which is the container size*/
  /* notes */ 'The serving size is 85 g; the container size is 284 g, so the data had to be scaled by a factor of 284/85.'),

  ('TJ Organic Couscous','Trader Joe''s Organic Couscous',NULL,1284,
  /* broad food type */ 'Semolina',
  /* fat-related columns */ 0,0,0,0,0,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 0,528,
  /* carbohydrate-related columns */ 264,15.1,0,
  /* protein-related columns */ 45.3,
  /* columns for commonly reported vitamins and minerals (other than sodium) */ NULL,NULL,0,75.6,3.78,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* notes */ 'The serving size is 45 g; the container size is 340 g, so the data had to be scaled by a factor of 340/45.'),

  ('Whole Foods Organic Multigrain and Seed Sandwich Bread','Whole Foods Organic Multigrain and Seed Sandwich Bread 22 oz','https://www.wholefoodsmarket.com/product/365-by-whole-foods-market-organic-sprouted-multigrain-seed-sandwich-bread-22-oz-b082n5n842',1530,
  /* broad food type */ 'Wheat bread',
  /* fat-related columns */ 25.5,0,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 2720,0,
  /* carbohydrate-related columns */ 272,51,51,
  /* protein-related columns */ 68,
  /* columns for commonly reported vitamins and minerals (other than sodium) */ NULL,NULL,0,0,13.6,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'I multiplied the information for one slice at https://www.wholefoodsmarket.com/product/365-by-whole-foods-market-organic-sprouted-multigrain-seed-sandwich-bread-22-oz-b082n5n842 with the number of slices (17).'),

  ('Kite Hill Vanilla Almond Yogurt (small)','Kite Hill Vanilla Almond Milk Yogurt, 5.3 Ounces, Dairy Free','https://www.amazon.com/Kite-Hill-Vanilla-Almond-Yogurt/dp/B06ZZCR5NJ',150,
  /* broad food type */ 'Vegan probiotic yogurt',
  /* fat-related columns */ 8,0.5,0,NULL,NULL,
  /* cholesterol */ 0,
  /* sodium and potassium (mostly from salts) */ 10,NULL,
  /* carbohydrate-related columns */ 19,2,12,
  /* protein-related columns */ 3,
  /* columns for commonly reported vitamins and minerals (other than sodium and potassium) */ NULL,NULL,NULL,44,1,
  /* columns for other less commonly reported vitamins and minerals */ NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  /* special oxalate column added in light of risk of kidney stones */ NULL,
  /* notes */ 'The information on the webpage already provides nutrition information for the full container.');

/* The list below is for food types for which we either cannot obtain
   nutritional information or don't want to spend the effort right
   now; having them in the table has other benefits such as data
   validation. */

/* Spices, condiments, and seasonings -- these don't have nutritional information to speak of, or it's very hard to abstract out the nutritional information */
insert into food_types(short_name, long_name, url, notes) values
  ('Lemon','Lemon',NULL,'I just squeeze drops from the lemon rather than having the whole lemon, so any nutritional information for the whole lemon would be misleading.'),
  ('Himalayan Fine Pink Salt','Himalayan Fine Pink Salt',NULL,'I bought this as a one-off for saltwater rinsing for the Portland trip, so including it in nutritional information would be misleading.'),
  ('TJ Turmeric','Trader Joe''s Turmeric Powder 2 oz','https://www.amazon.com/Trader-Joes-Turmeric-2-Pack/dp/B00JU4BQ1Y','I use this turmeric powder for seasoning my prepared meals.'),
  ('TJ Cumin','Trader Joe''s Ground Cumin 1.7 oz','https://www.amazon.com/Trader-Joes-Ground-Cumin-NET/dp/B07G1BV593','I use this ground cumin for seasoning my prepared meals.'),
  ('TJ Cayenne Pepper','Trader Joe''s Cayenne Pepper','https://www.ebay.com/itm/175363234738','I use a little of this cayenne pepper as seasoning. It''s generally less in amount than the turmeric and cumin, and I might skip it in case of a sore throat.'),
  ('TJ Cinnamon','Trader Joe''s Ground Cinnamon','https://www.amazon.com/Trader-Joes-Ground-Cinnamon-Pack/dp/B07TH176BQ','I put a small amount of this as seasoning. I started using this as there was some left over in my group house. I also accidentally bought another bottle on 2023-08-11, so I may continue using it for some time.');

insert into food_types(short_name, long_name, notes) values
  /* Udupi Palace */
  ('Udupi Palace spinach masala dosa','Udupi Palace spinach masala dosa with sambhar, white chutney, and red chutney','I generally order takeout for this when going to Trader Joe''s for grocery shopping.'),
  ('Udupi Palace spring dosa','Udupi Palace spring dosa with sambhar, white chutney, and red chutney','I got this by mistake once when ordering the spinach masala dosa.'),
  ('Udupi Palace bisi bele bath','Udupi Palace bisi bele bath (dine-in) with papad, raita, and pickles','I generally have this dish when dining in at Udupi Palace.'),
  ('Udupi Palace sambhar','Udupi Palace sambhar','I sometimes order this as an extra dish when dining in at Udupi Palace.'),
  ('Udupi Palace sambhar (small)','Udupi Palace sambhar (small)','I sometimes order this as an extra dish when dining in at Udupi Palace.'),
  ('Udupi Palace medu vada','Udupi Palace medu vada','I had this once when dining in with a friend at Udupi Palace.'),
  /* Mehak Indian Cuisine */
  ('Mehak Indian Cuisine standard set','Mehak Indian Cuisine standard set: two colored rices (complementary), aloo gobi, aloo saag, vegetable masala, two dal soups','I used to get one takeout of this every 2-3 weeks from September 2020 to (approximately) May 2023. I stopped after switching to part-time work and adding potatoes to my home meal prep.'),
  ('Mehak Indian Cuisine chana masala','Mehak Indian Cuisine chana masala','I have occasionally ordered this as an additional dish in Mehak Indian Cuisine takeout, on top of my standard set.'),
  ('Mehak Indian Cuisine bengan bharta','Mehak Indian Cuisine bengan bharta','I have occasionally ordered this as an additional dish in Mehak Indian Cuisine takeout, on top of my standard set.'),
  ('Mehak Indian Cuisine dal soup','Mehak Indian Cuisine dal soup','The dal soup is part of my standard set (2 dal soups in a standard set) but I have on occasion ordered additional dal soups.'),
  /* Bangkok Thai Cuisine */
  ('Bangkok Thai Cuisine white rice','Bangkok Thai Cuisine white rice','I used to get this as takeout from Bangkok Thai Cuisine occasionally, generally when I was running out of tortillas and wanted to get something quickly. I stopped after moving to a different part of town that was farther from the restaurant.'),
  ('Bangkok Thai Cuisine yellow curry tofu','Bangkok Thai Cuisine yellow curry tofu','I used to get this as takeout from Bangkok Thai Cuisine occasionally. I stopped after moving to a different part of town that was farther from the restaurant.'),
  /* Pakwan */
  ('Pakwan meal set','Pakwan meal set (dal, chana aloo, aloo sag, mixed veg curry)','I sometimes order this meal combination when I''m on a trip to San Francisco and have time to order takeout from Pakwan.'),
  ('Pakwan basmati rice','Pakwan basmati rice','On at least one occasion where I ordered takeout from Pakwan, I included basmati rice in the takeout. I didn''t do so on other occasions.'),
  /* Tender Greens */
  ('Tender Greens happy vegan salad','Tender Greens happy vegan salad','I occasionally visit Tender Greens for dine-in meals with others, and generally order the happy vegan salad during such meals.'),
  /* Revival Bar & Kitchen */
  ('Revival Bar & Kitchen paella','Revival Bar & Kitchen paella','I had this dish at the end-of-year group dinner for the company I worked for at the time.'),
  /* Tuk Tuk Thai */
  ('Tuk Tuk Thai jasmine rice','Tuk Tuk Thai jasmine rice','I had this by takeout once when I was feeling unwell and needed rice, but didn''t have a stock of rice and didn''t want to incur the time cost of buying + cooking rice.'),
  /* Imm Thai Street Food */
  ('Half spicy eggplant tofu and half yellow curry tofu','Imm Thai Street Food half spicy eggplant tofu and half yellow curry tofu','I had this special combination at a dine-in I did, sharing with another person, at Imm Thai Street Food.'),
  /* Kitava */
  ('Kitava Power Bowl','Kitava Power Bowl','I had this on 2023-11-29 when uenxpectedly dining in at Kitava.'),
  /* Tay Ho Oakland */
  ('Tay Ho Oakland Vegan Braised Eggplant, Tofu & Mushroom','Tay Ho Oakland Vegan Braised Eggplant, Tofu & Mushroom','I had this on 2024-03-27 as part of lunch with work colleagues near the Oakland WeWork.'),
  /* India House Oregon */
  ('India House Oregon rice','India House Oregon rice','I had this for takeout on 2024-06-03 in Portland.'),
  ('India House Oregon aloo sag','India House Oregon aloo sag','I had this for takeout on 2024-06-03 in Portland.'),
  ('Dil Se Indian Cuisine half chana masala and half aloo gobi','Dil Se Indian Cuisine half chana masala and half aloo gobi','I had this for takeout on 2024-06-04 in Portland.'),
  /* Asha Tea House */
  ('Asha Tea House ginger honey tea','Asha Tea House ginger honey tea','I have this on the occasional visit to Asha Tea House, usually whne meeting up with other people.');
