drop table if exists interpolated_nutrient_consumption;

create table interpolated_nutrient_consumption(
  `consumption_date` date primary key,
  `calories` decimal(21,6),
  `weight_in_grams` decimal(21,6),
  `volume_in_ml` decimal(21,6),
  `total_fat_in_grams` decimal(21,6),
  `saturated_fat_in_grams` decimal(21,6),
  `trans_fat_in_grams` decimal(21,6),
  `monounsaturated_fat_in_grams` decimal(21,6),
  `polyunsaturated_fat_in_grams` decimal(21,6),
  `cholesterol_in_mg` decimal(21,6),
  `sodium_in_mg` decimal(21,6),
  `potassium_in_mg` decimal(21,6),
  `total_carb_in_grams` decimal(21,6),
  `fiber_in_grams` decimal(21,6),
  `sugars_in_grams` decimal(21,6),
  `protein_in_grams` decimal(21,6),
  `vitamin_a_in_mcg` decimal(21,6),
  `vitamin_c_in_mg` decimal(21,6),
  `vitamin_d_in_mcg` decimal(21,6),
  `calcium_in_mg` decimal(21,6),
  `iron_in_mg` decimal(21,6),
  `vitamin_b6_in_mg` decimal(21,6),
  `vitamin_b12_in_mcg` decimal(21,6),
  `vitamin_e_in_mg` decimal(21,6),
  `vitamin_k_in_mcg` decimal(21,6),
  `magnesium_in_mg` decimal(21,6),
  `phosphorus_in_mg` decimal(21,6),
  `zinc_in_mg` decimal(21,6),
  `copper_in_mg` decimal(21,6),
  `oxalate_in_mg` decimal(21,6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into interpolated_nutrient_consumption
select consumption_date,
coalesce(sum(calories), 0),
coalesce(sum(weight_in_grams), 0),
coalesce(sum(volume_in_ml), 0),
coalesce(sum(total_fat_in_grams), 0),
coalesce(sum(saturated_fat_in_grams), 0),
coalesce(sum(trans_fat_in_grams), 0),
coalesce(sum(monounsaturated_fat_in_grams), 0),
coalesce(sum(polyunsaturated_fat_in_grams), 0),
coalesce(sum(cholesterol_in_mg), 0),
coalesce(sum(sodium_in_mg), 0),
coalesce(sum(potassium_in_mg), 0),
coalesce(sum(total_carb_in_grams), 0),
coalesce(sum(fiber_in_grams), 0),
coalesce(sum(sugars_in_grams), 0),
coalesce(sum(protein_in_grams), 0),
coalesce(sum(vitamin_a_in_mcg), 0),
coalesce(sum(vitamin_c_in_mg), 0),
coalesce(sum(vitamin_d_in_mcg), 0),
coalesce(sum(calcium_in_mg), 0),
coalesce(sum(iron_in_mg), 0),
coalesce(sum(vitamin_b6_in_mg), 0),
coalesce(sum(vitamin_b12_in_mcg), 0),
coalesce(sum(vitamin_e_in_mg), 0),
coalesce(sum(vitamin_k_in_mcg), 0),
coalesce(sum(magnesium_in_mg), 0),
coalesce(sum(phosphorus_in_mg), 0),
coalesce(sum(zinc_in_mg), 0),
coalesce(sum(copper_in_mg), 0),
coalesce(sum(oxalate_in_mg), 0)
from interpolated_food_and_nutrient_consumption
group by consumption_date;
