create table interpolated_food_and_nutrient_consumption(
  `consumption_date` date,
  `food_type` varchar(200),
  `broad_food_type` varchar(200),
  `interpolated_quantity` decimal(8,4),
  `calories` decimal(21,6),
  `weight_in_grams` decimal(21,6),
  `volume_in_ml` decimal(21,6),
  `total_fat_in_grams` decimal(21,6),
  `saturated_fat_in_grams` decimal(21,6),
  `trans_fat_in_grams` decimal(21,6),
  `monounsaturated_fat_in_grams` decimal(21,6),
  `polyunsaturated_fat_in_grams` decimal(21,6),
  `cholesterol_in_mg` decimal(21,6),
  `sodium_in_mg` decimal(21,6),
  `potassium_in_mg` decimal(21,6),
  `total_carb_in_grams` decimal(21,6),
  `fiber_in_grams` decimal(21,6),
  `sugars_in_grams` decimal(21,6),
  `protein_in_grams` decimal(21,6),
  `vitamin_a_in_mcg` decimal(21,6),
  `vitamin_c_in_mg` decimal(21,6),
  `vitamin_d_in_mcg` decimal(21,6),
  `calcium_in_mg` decimal(21,6),
  `iron_in_mg` decimal(21,6),
  `vitamin_b6_in_mg` decimal(21,6),
  `vitamin_b12_in_mcg` decimal(21,6),
  `vitamin_e_in_mg` decimal(21,6),
  `vitamin_k_in_mcg` decimal(21,6),
  `magnesium_in_mg` decimal(21,6),
  `phosphorus_in_mg` decimal(21,6),
  `zinc_in_mg` decimal(21,6),
  `copper_in_mg` decimal(21,6),
  `oxalate_in_mg` decimal(21,6),
  primary key (consumption_date, food_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into interpolated_food_and_nutrient_consumption
select consumption_date, food_type, broad_food_type,
coalesce(sum(interpolated_quantity), 0),
coalesce(sum(interpolated_quantity * calories), 0),
coalesce(sum(interpolated_quantity * weight_in_grams), 0),
coalesce(sum(interpolated_quantity * volume_in_ml), 0),
coalesce(sum(interpolated_quantity * total_fat_in_grams), 0),
coalesce(sum(interpolated_quantity * saturated_fat_in_grams), 0),
coalesce(sum(interpolated_quantity * trans_fat_in_grams), 0),
coalesce(sum(interpolated_quantity * monounsaturated_fat_in_grams), 0),
coalesce(sum(interpolated_quantity * polyunsaturated_fat_in_grams), 0),
coalesce(sum(interpolated_quantity * cholesterol_in_mg), 0),
coalesce(sum(interpolated_quantity * sodium_in_mg), 0),
coalesce(sum(interpolated_quantity * potassium_in_mg), 0),
coalesce(sum(interpolated_quantity * total_carb_in_grams), 0),
coalesce(sum(interpolated_quantity * fiber_in_grams), 0),
coalesce(sum(interpolated_quantity * sugars_in_grams), 0),
coalesce(sum(interpolated_quantity * protein_in_grams), 0),
coalesce(sum(interpolated_quantity * vitamin_a_in_mcg), 0),
coalesce(sum(interpolated_quantity * vitamin_c_in_mg), 0),
coalesce(sum(interpolated_quantity * vitamin_d_in_mcg), 0),
coalesce(sum(interpolated_quantity * calcium_in_mg), 0),
coalesce(sum(interpolated_quantity * iron_in_mg), 0),
coalesce(sum(interpolated_quantity * vitamin_b6_in_mg), 0),
coalesce(sum(interpolated_quantity * vitamin_b12_in_mcg), 0),
coalesce(sum(interpolated_quantity * vitamin_e_in_mg), 0),
coalesce(sum(interpolated_quantity * vitamin_k_in_mcg), 0),
coalesce(sum(interpolated_quantity * magnesium_in_mg), 0),
coalesce(sum(interpolated_quantity * phosphorus_in_mg), 0),
coalesce(sum(interpolated_quantity * zinc_in_mg), 0),
coalesce(sum(interpolated_quantity * copper_in_mg), 0),
coalesce(sum(interpolated_quantity * oxalate_in_mg), 0)
from interpolated_food_consumption left join food_types
on interpolated_food_consumption.food_type = food_types.short_name
group by consumption_date, food_type;
