create table pulse_oximeter_readings(
  reading_date date,
  index_within_reading_date integer,
  finger enum('right index finger','left index finger'),
  duration_in_seconds integer,
  heart_rate_min_bpm integer,
  heart_rate_max_bpm integer,
  spo2_min integer,
  spo2_max integer,
  within_an_hour_after_exercise boolean,
  within_two_hours_after_eating boolean,
  notes varchar(2000),
  primary key (reading_date, index_within_reading_date),
  check(spo2_min >= 60 and spo2_min <= 100),
  check(spo2_max >= 65 and spo2_max <= 100),
  check(spo2_min <= spo2_max),
  check(heart_rate_min_bpm <= heart_rate_max_bpm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into pulse_oximeter_readings(reading_date, index_within_reading_date, finger, duration_in_seconds, heart_rate_min_bpm, heart_rate_max_bpm, spo2_min, spo2_max, within_an_hour_after_exercise, within_two_hours_after_eating, notes) values
  /* 2024-07-13 */
  ('2024-07-13',1,'right index finger',120,42,51,94,97,false,false,'This reading was taken the morning after my Tdap vaccine booster dose, from 10:14:00 AM to 10:16:00 AM, with the start happening about 30-45 seconds after I put my finer in the pulse oximeter. Associated blood pressure + heart rate readings taken a few minutes prior were 92/63/46 and 97/65/48, so the heart rate range is consistent with those values. The measured heart rate started out around the middle of the range (45-48 bpm) then went up briefly to 51 bpm and later went down briefly to 42 bpm.'),
  ('2024-07-13',2,'right index finger',120,41,51,97,99,false,false,'This reading was taken shortly after returning from a brief shopping trip. I felt like my heart was racing a little bit, so I was curious to see what the pulse oximeter would show for this reading compared to the reading earlier in the day. I kept an eye on the data from 11:52:00 AM to 11:54:00 AM. Surprisingly, the heart rate range was very similar to before, but the SpO2 was a little higher.'),
  /* 2024-07-17 */
  ('2024-07-17',1,'right index finger',120,76,87,97,97,true,false,'This reading was taken a few minutes after returning from my morning jogging. The jogging today was fairly typical: about 1.7 miles jogging and 0.3 miles return walking. The heart rate measurement starts at 11:12:00, a few tens of seconds after I inserted my finger in the pulse oximeter, and continues till 11:14:00. The reading was initially 87 bpm, then went down to around 80 bpm, with a brief dip to 76 bpm. The SpO2 stayed steady at 97%.'),
  /* 2024-07-19 */
  ('2024-07-19',1,'right index finger',120,61,69,95,97,false,false,'This reading was about an hour after eating; I had gone jogging earlier in the morning. The reading was taken by me in conjunction with the use of a stethoscope (chest side) to listen to my heartbeat. I was using the pulse oximeter mainly to verify that what I was hearing as the heartbeat matched up with what the pulse oximeter showed. I confirmed this was the case. I looked at measurements over a period of about two minutes from 1:57:38 PM onward. The measured value was mostly in the 63-66 bpm range, with a brief spike to 69 bpm and a brief drop to 61 bpm.'),
  /* 2024-07-20 */
  ('2024-07-20',1,'right index finger',120,55,67,96,97,false,false,'This reading was taken a few minutes after returning from shopping. As it had been hot and I had subjectively experienced more heart activity, I decided to take this reading. I started recording about a minute after putting my finger in the pulse oximeter, starting 10:33:00 AM and going till 10:35:00 AM. For the most part, the heart rate was in the 59-64 bpm range, but it did dip briefly to 55 bpm and rise briefly to 67 bpm.'),
  /* 2024-07-22 / 2024-07-23 */
  ('2024-07-22',1,'right index finger',60,48,57,97,98,false,false,'This reading was taken at night, lying down, at the start of 20-minute relaxation period before going to sleep. I wasn''t looking at a clock when doing this so I don''t know my duration of monitoring for sure.'),
  ('2024-07-23',1,'right index finger',60,50,60,99,100,false,false,'This reading was taken about 20 minutes after the previous reading, with a lying-down relaxation period in between. As the previous reading was shortly before midnight, this reading was technically taken the next day. I wasn''t looking at a clock when doing this so I don''t know my duration of monitoring for sure.'),
  /* 2024-07-23 */
  ('2024-07-23',2,'right index finger',60,54,58,98,98,false,false,'This reading was taken at night, shortly before getting ready for bed, at the start of a 10-minute relaxation period. I started looking at the measurement at 9:55:00 PM, about 30 seconds after putting the pulse oximeter in.'),
  ('2024-07-23',3,'right index finger',60,55,60,97,98,false,false,'This was a followup reading after a 10-minute relaxation period following the previous reading.'),
  /* 2024-07-31 */
  ('2024-07-31',1,'left index finger',120,53,61,97,97,false,false,'This was based on a two-minute observation period from 4:54:15 PM to 4:56:15 PM. The heart rate mostly stayed between 54 and 58 bpm, with a brief dive to 53 early on and a brief rise to 61 toward the end.'),
  /* 2024-08-01 */
  ('2024-08-01',1,'left index finger',60,50,62,96,97,false,false,'This was based on a one-minute observation period from 2:53:30 PM to 2:54:30 PM. The impetus for the observation is that I felt like my heart was beating faster than usual. The heart rate started out around 54-56 bpm, dropped to 51 bpm, then rose to 62 bpm, then dropped again down to 50 bpm and then went up a little bit.'),
  /* 2024-08-10 */
  ('2024-08-10',1,'right index finger',60,50,58,94,97,false,false,'This reading was taken shortly after blood pressure readings. The observation period was from 9:28:15 AM to 9:29:15 AM. My heart rate rose from around 51 bpm (with a brief dip to 50 bpm) to 58 bpm, then came back down to around 51 bpm. My SpO2 dropped from 97% to 95%, then briefly dipped to 94% before returning to 95%.'),
  /* 2024-08-14 */
  ('2024-08-14',1,'right index finger',120,50,55,97,98,false,false,'This reading was taken at night; I observed the reading from 10:13:00 PM to 10:15:00 PM. The reading started around and mostly stayed in the range of 52-53 bpm, with occasional drops to 50 bpm and increases to 55 bpm.'),
  /* 2024-08-18 */
  ('2024-08-18',1,'right index finger',120,42,54,99,99,false,false,'This reading was taken in the morning about 25 minutes after being seated and working on my computer after my morning bowel movement. The reading was observed from 8:34:00 AM to 8:36:00 AM. Prior the observation, it had dropped from 58 bpm to 50 bpm, with the initial high likely being due to movements involved in putting the pulse oximeter on. During the observation period, it started at 50 bpm, fluctuated arounf 49-51, then briefly rose to 54 bpm, then dropped to around 45-47 bpm. Right near the end of the observation period, it dropped to 42 bpm. My SpO2 started at 100% before the start of the observation period but was at 99% throughout the observation period.'),
  /* 2024-08-22 */
  ('2024-08-22',1,'left index finger',120,48,58,100,100,false,false,'This reading was taken in the morning before eating any food. I spent a few minutes with my right index finger but didn''t get a reading, though the suggested frequency was about 45-55 bpm. I then switched to the left index finger, that briefly flashed readings of 44 bpm and 56 bpm, then blanking out. It finally settled into showing a steady heart rate and I monitored it from 10:43:00 to 10:45:00 to get the reported range.'),
  /* 2024-08-24 */
  ('2024-08-24',1,'right index finger',60,53,60,97,97,false,false,'The context of this reading was that I took it shortly after my first breath test, to see if anxiety or excitement around it had any effect on my heart rate. Judging from the readings, any effect it had turned out to be small. I took this reading around 5:25 PM; I didn''t note down the exact time. I started recording about 30 seconds after putting my finger in. At the time of starting recording, the heart rate was about 58-59 bpm; it then dropped down to 53 bpm, then briefly rose to 60 bpm, then dropped back down to 53 bpm. The SpO2 remained at 97% throughout the measurement period, though it had been at 98% prior to the measurement period (right when I inserted my finger).'),
  /* 2024-08-25 */
  ('2024-08-25',1,'right index finger',60,83,89,95,97,true,false,'This reading was taken from 9:58:40 AM to 9:59:40 AM, a few minutes after returning from jogging/walking (about 1.4 miles and 0.6 miles respectively). When I initially put my finger in the pulse oximeter, the reading was at 95 bpm and shot up to 101 bpm, but it was trending downward. By the time I started measuring, it was at 88 bpm. It went down to about 83 bpm, then shot up to 89 bpm, then went back down to about 83 bpm.'),
  /* 2024-08-26 */
  ('2024-08-26',1,'right index finger',60,74,86,96,97,false,true,'This reading was taken about 1.5 hours after eating, but just a couple of minutes after sitting down from urination. I was feeling like my heart rate is a little high, and indeed it was! I measured from 2:04:20 PM to 2:05:20 PM, about a minute after initially putting my finger in. The reading at the start of my measurement was 76 bpm; it went up to 86 bpm and later went down to 74 bpm before rising up again to the 76-80 bpm range.'),
  ('2024-08-26',2,'right index finger',60,60,68,96,97,false,false,'This reading was taken almost 3 hours after eating, from 3:18:30 PM to 3:19:30 PM. I started recording about a minute after I put my fignger in. It started out around 63-64 bpm, and fluctuated downward to 60 bpm, up to 66 bpm, then back down to 60 bpm, and toward the end went up to 68 bpm.'),
  /* 2024-08-27 */
  ('2024-08-27',1,'right index finger',60,61,71,97,98,false,false,'This reading was taken in the morning, in response to a subjective sensation of a high heart rate. I started measuring at 8:27:00 AM, about 30 seconds after putting my finger in, and continued till 8:28:00 AM. The heart rate started at 64-65 bpm in the beginning, fluctuated up to 66 and down to 61, then toward the end it climbed to 71 bpm.'),
  ('2024-08-27',2,'right index finger',120,66,74,96,97,false,false,'This reading was taken in the afternoon, about 2.5 hours after finishing my first meal. I started measuring at 2:50:15 PM, about 40-60 seconds after putting my finger in, and continued till 2:52:15 PM. Within the period I recorded, the heart rate mostly stayed around 70-71 bpm, with occasional fluctuation in the 68-72 bpm range, and one increase to 74 bpm and one drop to 66 bpm. This reading continues to be high relative to my usual, and is indicative that something is going on.'),
  /* 2024-08-28 */
  ('2024-08-28',1,'right index finger',75,50,55,97,100,false,false,'This reading was taken from 9:52:15 AM to 9:53:30 AM, before starting my first meal. I took this reading to assess my recovery from the heart rate spike of the last two days. The heart rate started around 52-55 bpm and later dropped to around 50 bpm before rising back up to around 54 bpm. Overall, my heart rate is now within the normal range, suggesting recovery.'),
  /* 2024-08-29 */
  ('2024-08-29',1,'left index finger',135,46,62,99,100,false,false,'This reading was taken from 8:39:15 AM to 8:41:30 AM with my left index finger, after I initially tried with my right index finger but failed to get a reading. The reading was mostly in the range of 48 bpm to 52 bpm, with occasional fluctuations down to 46 bpm and up to 54 bpm. There was, however, one brief spike up to 62 bpm for a few seconds.'),
  /* 2024-09-02 */
  ('2024-09-02',1,'right index finger',120,44,50,97,100,false,false,'This reading was taken from 10:57:30 AM to 10:59:30 AM. This was over an hour after a bowel movement and before eating or exercise. The reading started out in the 48-50 bpm range with SpO2 around 98-99%; toward the end, the heart rate dropped to the 44-46 bpm range. The SpO2 briefly dropped to 97% and briefly rose to 100% over the interval.'),
  /* 2024-09-06 */
  ('2024-09-06',1,'right index finger',180,48,61,92,99,false,false,'This reading was taken from 9:17:30 AM to 9:20:30 AM. My reading initially started to 50 bpm / 99% SpO2, then dropped to 48 bpm / 99% SpO2 and stayed there for a while. Then, over time, the heart rate rose to arond 55 bpm, and the SpO2 dropped to about 96%. The ehart rate then had two brief spies  to 60 bpm and 61 bpm respectively, returning to the 50-55 bpm range each time. The SpO2 continued to drop to around 93-94%, with a brief dip to 92%.'),
  ('2024-09-06',2,'right index finger',90,74,88,96,98,true,false,'This reading was taken about 3 minutes after sitting down after returning from jogging. The reading was taken over a period of 90 seconds from 10:18:45 AM to 10:20:15 AM. The reading started in the range of 78-85 bpm, and mostly stayed there, with a brief spike up to 88 bpm and a brief drop down to 74 bpm. The SpO2 was around 97% with a brief increase to 98% and a brief drop to 96%.'),
  ('2024-09-06',3,'right index finger',60,58,68,97,99,false,false,'This reading was taken about 1 hour 25 minutes after returning from jogging. The reading was taken over a period of 60 seconds from 11:39:15 AM to 11:40:15 AM. Prior to starting to take the reading, when I first put my finger in the pulse oximeter, the heart rate reading was around 82, but it dropped quickly to 68 bpm and then slowed down; that''s when I started measuring. The heart rate fluctuated in the range of 58 bpm to 68 bpm, mostly staying in the middle. The SpO2 started out around 99% and dropped to 98% and then 97%.'),
  /* 2024-09-10 */
  ('2024-09-10',1,'right index finger',120,58,69,98,98,false,false,'This reading was observed between 3:50:15 PM and 3:52:15 PM, starting about a minute after I put my finger in the pulse oximeter. For the most part, the reading was 58-65 bpm, mostly staying at around 61-64 bpm. Toward the end, there was a brief spike to 69 bpm before returning back down to the 58-65 bpm range. This reading was taken about 2 hours 20 minutes after finishing my last meal, so it isn''t within the two-hour range needed for the boolean column, but close enough to explain the higher reading compared to morning readings.'),
  /* 2024-09-11 */
  ('2024-09-11',1,'right index finger',90,52,58,98,98,false,true,'This reading was observed between 9:03:45 PM and 9:05:15 PM, starting a few seconds after I put my finger in the pulse oximeter. The SpO2 reading stayed at 98% throughout. The heart rate started around 52 bpm, then rose to around 58 bpm, then dropped to around 54 bpm, and continued to fluctuate in the 52-58 bpm range.'),
  ('2024-09-11',2,'right index finger',135,44,55,97,100,false,false,'This reading was observed between 10:21:45 PM and 10:24:00 PM, starting about a minute after I put my finger in the pulse oximeter. The SpO2 started at 98%, eventually rose to 100%, and dropped to 97% near the end. The heart rate was largely in the 48-52 bpm range, with a brief drop to 44 bpm in the middle and a brief rise to 55 bpm near the end.'),
  /* 2024-09-12 */
  ('2024-09-12',1,'right index finger',60,66,71,98,98,false,true,'This reading was observed between 4:11:45 PM and 4:12:45 PM, starting about 30-60 seconds after I put my finger in the pulse oximeter. The SpO2 reading stayed at 98% throughout. The heart rate fluctuated between 66 bpm and 71 bpm, with fluctuation throughout the range for the whole duration.'),
  /* 2024-09-13 */
  ('2024-09-13',1,'right index finger',60,46,50,95,97,false,false,'This reading was taken in the morning between 8:45:45 AM and 8:46:45 AM, with observation starting about a minute after putting my finger in the pulse oximeter. This was after my bowel movement and before exercise or eating. The reading started out at 46 bpm and 96% SpO2. The heart rate rose gradually to 50 bpm and then dropped again, fluctuating in the range. The SpO2 fluctuated own to 95% and up to 97% briefly, but mostly stayed around 96%.'),
  /* 2024-09-15 */
  ('2024-09-15',1,'right index finger',60,65,71,98,99,false,true,'This reading was taken in the afternoon between 2:57:45 PM and 2:58:45 PM, with observation starting about a minute after putting my finger in the pulse oximeter. I had finished my first meal of the day at 1:22 PM. Prior to the observation period, the reading gradually rose from about 53 bpm to 65 bpm. During the observation period, the reading started out at 65-66 bpm, then gradually rose to about 71 bpm and then dropped back again. The SpO2 fluctuated between 98% and 99%.'),
  /* 2024-09-18 */
  ('2024-09-18',1,'right index finger',60,48,52,98,99,false,false,'This reading was taken in the afternoon between 3:46:45 PM and 3:47:45 PM, with obsevation starting about a minute after putting my finger in the pulse oximeter. Prior to observation, my heart rate dropped from 68 bpm gradually down to 52 bpm; the high initial heart rate might be due to the the hustle of movement involved in putting the pulse oximeter on. During the observation period, the reading dropped from 52 bpm to 50 bpm, then fluctuated in the 50-52 bpm, later widening the fluctuation to 48-52 bpm. The SpO2 was 98% initially and rose to 99% (and then stayed there).'),
  /* 2024-09-20 */
  ('2024-09-20',1,'right index finger',90,58,68,97,99,false,false,'This reading was taken in the afternoon from 5:10:45 PM to 5:12:15 PM, with observation starting about 15 seconds after putting my finger in the pulse oximeter. My heart rate started out around 65-68 bpm and then dropped to the 58-63 bpm range toward the end of the observation period. The SpO2 started at 99% and dropped to 97% at the end of the observation period. The readings were taken about 2.5 hours after I finished my first meal at 2:44 PM.'),
  /* 2024-09-25 */
  ('2024-09-25',1,'right index finger',60,55,63,98,99,false,false,'This reading was taken in the evening from 5:59:30 PM to 6:00:30 PM, about three hours after finishing my first meal. As I had just gotten up and fetched the pulse oximeter right before putting my finger in it, I waited over a minute before starting observation. The reading started at 55 bpm at the time of starting observation, gradually went up to about 61 bpm, went down a bit, then up to 63 bpm, then went down into the high 50s again.'),
  /* 2024-09-27 */
  ('2024-09-27',1,'right index finger',60,61,69,97,97,false,true,'This reading was taken in the afternoon between 3:21:45 PM and 3:22:45 PM, starting about 30-60 seconds after I inserted my finger in the pulse oximeter. I had finished my first meal at 1:30 PM. The reading started in the 63-65 bpm range, then went down to 61 bpm, returned gradually through 62, 63, and 64 to 65 bpm, then briefly spiked to 67 and 69 bpm and finally dropped back down to around 65 bpm. The SpO2 stayed at 97% throughout.'),
  /* 2024-09-28 */
  ('2024-09-28',1,'right index finger',60,47,54,95,96,false,false,'This reading was taken in the morning between 10:58:00 AM and 10:59:00 AM, starting about 30-60 seconds after I inserted my finger in the pulse oximeter. This reading was before eating or exercise. Prior to observation, the reading was at 59 bpm but clearly going down. I started the reading once it was sort-of stable around 52 bpm. It went down to 47 bpm, then rose back up and spiked to 54 bpm, then went down again to 49 bpm, and finally ended in the 52-53 bpm range. The SpO2 started around 97% when I inserted my finger, but had reached 95% by the start of the observation period, and stayed there for most of the period but went up to 96% near the end. I counted about six total breaths during the observation period.'),
  /* 2024-10-04 */
  ('2024-10-04',1,'right index finger',60,53,60,97,98,false,true,'This reading was taken in the afternoon between 3:35:00 PM and 3:36:00 PM, starting about 30-60 seconds after I inserted my finger in the pulse oximeter. This reading was almost two hours after finishing my first meal. Prior to recording, the reading started at 75 bpm (likely due to movement shortly before starting) and quickly went down to about 58 bpm, after which it gradually dropped further. When I started recording, the heart rate reading was in the 53-56 bpm range and the SpO2 was 98%. The heart rate reading fluctuated in the 53-60 bpm range through the minute, and the SpO2 dropped from 98% to 97%.'),
  /* 2024-10-05 */
  ('2024-10-05',1,'right index finger',120,46,56,98,98,false,false,'This reading was taken at night, from 11:21:00 PM to 11:23:00 PM, over five hours after the completion of my last meal. I started recording about 30-60 seconds after inserting my finger in the pulse oximeter. Prior to recording, the reading started out at 60 bpm, then went to 58 bpm, then went down to 53 bpm and stayed in the 49-53 bpm range. When I started recording, it was 49 bpm, after which it dropped to 46 bpm briefly, then rose again to around 56 bpm and then fluctuated in the 50-55 bpm range.'),
  /* 2024-10-07 */
  ('2024-10-07',1,'right index finger',60,58,66,98,98,false,false,'This reading was taken from 3:44:00 PM to 3:45:00 PM, about 2.5 hours after I finished my first meal at 1:08 PM. I started recording about a minute after putting my finger in the pulse oximeter; prior to recording, the heart rate started at around 71 bpm and dropped into the 60s. During the recording period, the heart rate started around 58-82 bpm and toward the end was fluctuating in the 62-66 bpm range. The SpO2 stayed at 98% throughout the recording period. An unusual factor that might have affected my heart rate is the heat; outdoor temperature was around 87 degrees Fahrenheit and indoor temperature was in excess of 90 degrees Fahrenheit.'),
  /* 2024-10-08 */
  ('2024-10-08',1,'right index finger',120,47,58,98,100,false,false,'This reading was taken from 10:52:30 PM to 10:54:30 PM, a little over 2 hours after I finished my second meal at 8:37 PM. I started recording about 1-2 minutes after putting my finger in the pulse oximeter; prior to recording, the heart rate started at around 63 bpm and gradually dropped. When I started recording, it was at around 50-51 bpm, from where it dropped to around 47 bpm and then rose all the way to 58 bpm. It finally dropped back to around 50 bpm. The SpO2 started at around 100%, and gradually dropped into the 98-99% range.'),
  /* 2024-10-11 */
  ('2024-10-11',1,'right index finger',60,56,70,98,99,false,true,'This reading was taken between 9:33:00 PM and 9:34:00 PM, about 1.5 hours after I finished my second meal at 8:01 PM. I started recording about 30-45 seconds after putting my finger in the pulse oximeter. At the start of recording, the SpO2 was 98% and the heart rate was fluctuating in the 60-62 bpm range. The heart rate spiked to 70 bpm, then gradually came back down to 60 bpm, then went further down to 56 bpm and then got back up to around 59 bpm when I stopped recording. The SpO2 increased from 98% to 99% some time during the process and then stayed at 99%.'),
  /* 2024-10-13 */
  ('2024-10-13',1,'right index finger',60,49,55,99,100,false,false,'This reading was taken in the morning, between 8:40:30 AM and 8:41:30 AM, before eating and exercise. It was taken with the blood pressure cuff on my left arm (I used the right index finger for the reading) but prior to taking the blood pressure readings. I started observing about 30 seconds after putting my finger in the pulse oximeter. Within the observation period, the heart rate started around 49-50 bpm, then briefly rose to 55 bpm and later settled back in the 49-52 bpm range. The SpO2 fluctuated between 99% and 100% during the observation period. The heart rate range was consistent with the two point estimates (53 bpm and 49 bpm) obtained as part of the blood pressure readings I took immediately afterward.'),
  ('2024-10-13',2,'right index finger',60,61,75,98,98,true,false,'This reading was taken about ten minutes after returning from jogging + walking and about two minutes after finishing my dead hang. During the observation period, the reading started in the high 60s. It then rose to 75 bpm, then fell all the way down to 61 bpm. It ended at around the mid-60s. The SpO2 stayed at 98% throughout.'),
  /* 2024-10-17 */
  ('2024-10-17',1,'right index finger',60,46,54,98,99,false,false,'This reading was taken at night, between 10:44:00 PM and 10:45:00 PM. Within the observation period, the heart rate reading started out at 52 bpm and fluctuated within the 46-54 bpm range. The SpO2 started at 99% and ended at 98%, though I''m not totally sure that it started at 99% within the observation period.'),
  /* 2024-10-21 */
  ('2024-10-21',1,'right index finger',60,47,51,99,99,false,false,'This reading was taken at night, between 9:41:15 PM and 9:42:15 PM, about three hours after I finished my second meal at 6:51 PM. Within the observation period, the heart rate started at 48 bpm, stayed there for a while, then dipped to 47 bpm and then rose gradually to 50-51 bpm. The SpO2 stayed at 99% throughout.'),
  /* 2024-10-24 */
  ('2024-10-24',1,'right index finger',60,58,67,99,100,true,false,'This reading was taken between 10:25:15 AM and 10:26:15 AM, about 30 seconds after I started getting a reading. The pulse oximeter took about a minute or two to start showing a reading. This reading was taken about 15 minutes after returning from jogging. I also used the stethoscope to listen to my heartbeats while observing the pulse oximeter values. The heart rate started at 67 bpm, then gradually went down and reached around 58 bpm at the end. The SpO2 started at 100% and dropped to 99% toward the end of the minute.'),
  /* 2024-10-25 */
  ('2024-10-25',1,'right index finger',60,49,57,97,98,false,false,'This reading was taken between 10:39:30 PM and 10:40:30 PM, a few minutes after I put my finger in the pulse oximeter. The readings prior to the observation period had also been similar. Within the observation period, the heart rate rose from 49 bpm gradually to 57 bpm, then dropped and fluctuated within the range. The SpO2 went back-and-forth between 97% and 98% several times over the period. This reading was taken a little over three hours after I finished my second meal at 7:36 PM. Earlier the day, I had gotten my flu shot; see https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-10-25-flu-shot.md for details.'),
  /* 2024-10-29 */
  ('2024-10-29',1,'right index finger',60,44,48,95,100,false,false,'This reading was taken between 10:27:45 PM and 10:28:45 PM, starting about a minute after putting my finger in the pulse oximeter. This was almost four hours after I finished my second and last meal at 6:35 PM. The reading right when I put my finger in was about 65 bpm, but it dropped quickly into the 50s and then into the 40s. Over the course of the observation period, the reading started at 44 bpm, climbed up to about 48 bpm, and then fluctuated within the range. The SpO2 started at 100%, dropped gradually to 95%, and then rebounded to around 97%.'),
  /* 2024-11-04 */
  ('2024-11-04',1,'right index finger',90,54,62,99,100,false,false,'This reading was taken between 9:10:45 PM and 9:12:15 PM, starting about 1-2 minutes after putting my finger in the pulse oximeter. This was about 2.5 hours after finishing my second meal at 6:46 PM. During the observation period, my reading started in the 59-62 bpm range, then went down to the 54-57 bpm range, then rose again to the upper range. The SpO2 started at 99%, rose to 100%, and dropped back to 99%.'),
  /* 2024-11-18 */
  ('2024-11-18',1,'right index finger',60,58,63,95,97,false,false,'This reading was taken between 9:53:15 PM and 9:54:15 PM, about 2.5 hours after I finished my evening meal at 7:28 PM. It took several minutes after I inserted my finger in the pulse oximeter for it to start displaying a reading, and about a minute after that for the reading range to stabilize. The SpO2 started at 100% prior to the observation period but reached 97% by the start of the observation period, and during the observation period it fell to 96% and then to 95%. The heart rate started at 62 bpm, rose to 63 bpm, dropped to 58 bpm, and then rose back again and fluctuated in the 59-61 bpm range.'),
  /* 2024-12-14 */
  ('2024-12-14',1,'right index finger',60,60,71,95,98,false,false,'This reading was taken between 4:56:00 PM and 4:57:00 PM, about 2 hours 40 minutes after I finished my first meal at 2:16 PM. Although it''s outside the two-hour window after meals when heart rate tends to be more elevated, the larger size of winter meals likely means that heart rate stays somewhat elevated for longer, which might explain my heart rate being higher than my historical resting heart rate (I haven''t been able to get a successful morning reading with the pulse oximeter, likely because the pulse oximeter has difficulty getting a reading in the cold, so I can''t directly compare with a morning reading on a nearby day). I don''t know if this is relevant, but including it anyway: I had a blood draw the previous day (2024-12-13); see https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-12-13-blood-tests.md for details. The heart rate was around 60-62 bpm at the start of the interval, rose to 71 bpm, and dropped back down to 65 bpm near the end. This pulse oximeter reading was taken shortly after two blood pressure readings that both measured the heart rate as 60 bpm. The SpO2 started around 97-98% and then dropped to around 95-96%, then went back up to 97-98%, and then oscillated a little bit over the whole 95-98% range.'),
  /* 2025-02-26 */
  ('2025-02-26',1,'right index finger',60,71,77,97,97,false,true,'This reading was taken between 3:22:00 PM and 3:23:00 PM, about 1 hour 17 minutes after I finished my first meal at 2:05 PM. I put my finger in the pulse oximeter about 1-2 minutes before the observation period. This is the first time after a while that the pulse oximeter has succeeded in giving clear readings, and it likely reflects that the temperature has returned to normal. The indoor temperature at the time of taking the reading was about 72 degrees Fahrenheit. Within the observation period, the temperature started at 75 bpm, dropped to 71 bpm, then rose up to 76-77 bpm, then dropped again to around 71 bpm; it continued like this for a few cycles.');
