create table pulse_oximeter_readings(
  reading_date date,
  index_within_reading_date integer,
  finger enum('right index finger','left index finger'),
  duration_in_seconds integer,
  heart_rate_min_bpm integer,
  heart_rate_max_bpm integer,
  spo2_min integer,
  spo2_max integer,
  within_an_hour_after_exercise boolean,
  within_two_hours_after_eating boolean,
  notes varchar(2000),
  primary key (reading_date, index_within_reading_date),
  check(spo2_min >= 60 and spo2_min <= 100),
  check(spo2_max >= 65 and spo2_max <= 100),
  check(spo2_min <= spo2_max),
  check(heart_rate_min_bpm <= heart_rate_max_bpm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into pulse_oximeter_readings(reading_date, index_within_reading_date, finger, duration_in_seconds, heart_rate_min_bpm, heart_rate_max_bpm, spo2_min, spo2_max, within_an_hour_after_exercise, within_two_hours_after_eating, notes) values
  /* 2024-07-13 */
  ('2024-07-13',1,'right index finger',120,42,51,94,97,false,false,'This reading was taken the morning after my Tdap vaccine booster dose, from 10:14:00 AM to 10:16:00 AM, with the start happening about 30-45 seconds after I put my finer in the pulse oximeter. Associated blood pressure + heart rate readings taken a few minutes prior were 92/63/46 and 97/65/48, so the heart rate range is consistent with those values. The measured heart rate started out around the middle of the range (45-48 bpm) then went up briefly to 51 bpm and later went down briefly to 42 bpm.'),
  ('2024-07-13',2,'right index finger',120,41,51,97,99,false,false,'This reading was taken shortly after returning from a brief shopping trip. I felt like my heart was racing a little bit, so I was curious to see what the pulse oximeter would show for this reading compared to the reading earlier in the day. I kept an eye on the data from 11:52:00 AM to 11:54:00 AM. Surprisingly, the heart rate range was very similar to before, but the SpO2 was a little higher.'),
  /* 2024-07-17 */
  ('2024-07-17',1,'right index finger',120,76,87,97,97,true,false,'This reading was taken a few minutes after returning from my morning jogging. The jogging today was fairly typical: about 1.7 miles jogging and 0.3 miles return walking. The heart rate measurement starts at 11:12:00, a few tens of seconds after I inserted my finger in the pulse oximeter, and continues till 11:14:00. The reading was initially 87 bpm, then went down to around 80 bpm, with a brief dip to 76 bpm. The SpO2 stayed steady at 97%.'),
  /* 2024-07-19 */
  ('2024-07-19',1,'right index finger',120,61,69,95,97,false,false,'This reading was about an hour after eating; I had gone jogging earlier in the morning. The reading was taken by me in conjunction with the use of a stethoscope (chest side) to listen to my heartbeat. I was using the pulse oximeter mainly to verify that what I was hearing as the heartbeat matched up with what the pulse oximeter showed. I confirmed this was the case. I looked at measurements over a period of about two minutes from 1:57:38 PM onward. The measured value was mostly in the 63-66 bpm range, with a brief spike to 69 bpm and a brief drop to 61 bpm.'),
  /* 2024-07-20 */
  ('2024-07-20',1,'right index finger',120,55,67,96,97,false,false,'This reading was taken a few minutes after returning from shopping. As it had been hot and I had subjectively experienced more heart activity, I decided to take this reading. I started recording about a minute after putting my finger in the pulse oximeter, starting 10:33:00 AM and going till 10:35:00 AM. For the most part, the heart rate was in the 59-64 bpm range, but it did dip briefly to 55 bpm and rise briefly to 67 bpm.'),
  /* 2024-07-22 / 2024-07-23 */
  ('2024-07-22',1,'right index finger',60,48,57,97,98,false,false,'This reading was taken at night, lying down, at the start of 20-minute relaxation period before going to sleep. I wasn''t looking at a clock when doing this so I don''t know my duration of monitoring for sure.'),
  ('2024-07-23',1,'right index finger',60,50,60,99,100,false,false,'This reading was taken about 20 minutes after the previous reading, with a lying-down relaxation period in between. As the previous reading was shortly before midnight, this reading was technically taken the next day. I wasn''t looking at a clock when doing this so I don''t know my duration of monitoring for sure.'),
  /* 2024-07-23 */
  ('2024-07-23',2,'right index finger',60,54,58,98,98,false,false,'This reading was taken at night, shortly before getting ready for bed, at the start of a 10-minute relaxation period. I started looking at the measurement at 9:55:00 PM, about 30 seconds after putting the pulse oximeter in.'),
  ('2024-07-23',3,'right index finger',60,55,60,97,98,false,false,'This was a followup reading after a 10-minute relaxation period following the previous reading.'),
  /* 2024-07-31 */
  ('2024-07-31',1,'left index finger',120,53,61,97,97,false,false,'This was based on a two-minute observation period from 4:54:15 PM to 4:56:15 PM. The heart rate mostly stayed between 54 and 58 bpm, with a brief dive to 53 early on and a brief rise to 61 toward the end.'),
  /* 2024-08-01 */
  ('2024-08-01',1,'left index finger',60,50,62,96,97,false,false,'This was based on a one-minute observation period from 2:53:30 PM to 2:54:30 PM. The impetus for the observation is that I felt like my heart was beating faster than usual. The heart rate started out around 54-56 bpm, dropped to 51 bpm, then rose to 62 bpm, then dropped again down to 50 bpm and then went up a little bit.'),
  /* 2024-08-10 */
  ('2024-08-10',1,'right index finger',60,50,58,94,97,false,false,'This reading was taken shortly after blood pressure readings. The observation period was from 9:28:15 AM to 9:29:15 AM. My heart rate rose from around 51 bpm (with a brief dip to 50 bpm) to 58 bpm, then came back down to around 51 bpm. My SpO2 dropped from 97% to 95%, then briefly dipped to 94% before returning to 95%.'),
  /* 2024-08-14 */
  ('2024-08-14',1,'right index finger',120,50,55,97,98,false,false,'This reading was taken at night; I observed the reading from 10:13:00 PM to 10:15:00 PM. The reading started around and mostly stayed in the range of 52-53 bpm, with occasional drops to 50 bpm and increases to 55 bpm.'),
  /* 2024-08-18 */
  ('2024-08-18',1,'right index finger',120,42,54,99,99,false,false,'This reading was taken in the morning about 25 minutes after being seated and working on my computer after my morning bowel movement. The reading was observed from 8:34:00 AM to 8:36:00 AM. Prior the observation, it had dropped from 58 bpm to 50 bpm, with the initial high likely being due to movements involved in putting the pulse oximeter on. During the observation period, it started at 50 bpm, fluctuated arounf 49-51, then briefly rose to 54 bpm, then dropped to around 45-47 bpm. Right near the end of the observation period, it dropped to 42 bpm. My SpO2 started at 100% before the start of the observation period but was at 99% throughout the observation period.'),
  /* 2024-08-22 */
  ('2024-08-22',1,'left index finger',120,48,58,100,100,false,false,'This reading was taken in the morning before eating any food. I spent a few minutes with my right index finger but didn''t get a reading, though the suggested frequency was about 45-55 bpm. I then switched to the left index finger, that briefly flashed readings of 44 bpm and 56 bpm, then blanking out. It finally settled into showing a steady heart rate and I monitored it from 10:43:00 to 10:45:00 to get the reported range.'),
  /* 2024-08-24 */
  ('2024-08-24',1,'right index finger',60,53,60,97,97,false,false,'The context of this reading was that I took it shortly after my first breath test, to see if anxiety or excitement around it had any effect on my heart rate. Judging from the readings, any effect it had turned out to be small. I took this reading around 5:25 PM; I didn''t note down the exact time. I started recording about 30 seconds after putting my finger in. At the time of starting recording, the heart rate was about 58-59 bpm; it then dropped down to 53 bpm, then briefly rose to 60 bpm, then dropped back down to 53 bpm. The SpO2 remained at 97% throughout the measurement period, though it had been at 98% prior to the measurement period (right when I inserted my finger).'),
  /* 2024-08-25 */
  ('2024-08-25',1,'right index finger',60,83,89,95,97,true,false,'This reading was taken from 9:58:40 AM to 9:59:40 AM, a few minutes after returning from jogging/walking (about 1.4 miles and 0.6 miles respectively). When I initially put my finger in the pulse oximeter, the reading was at 95 bpm and shot up to 101 bpm, but it was trending downward. By the time I started measuring, it was at 88 bpm. It went down to about 83 bpm, then shot up to 89 bpm, then went back down to about 83 bpm.'),
  /* 2024-08-26 */
  ('2024-08-26',1,'right index finger',60,74,86,96,97,false,true,'This reading was taken about 1.5 hours after eating, but just a couple of minutes after sitting down from urination. I was feeling like my heart rate is a little high, and indeed it was! I measured from 2:04:20 PM to 2:05:20 PM, about a minute after initially putting my finger in. The reading at the start of my measurement was 76 bpm; it went up to 86 bpm and later went down to 74 bpm before rising up again to the 76-80 bpm range.'),
  ('2024-08-26',2,'right index finger',60,60,68,96,97,false,false,'This reading was taken almost 3 hours after eating, from 3:18:30 PM to 3:19:30 PM. I started recording about a minute after I put my fignger in. It started out around 63-64 bpm, and fluctuated downward to 60 bpm, up to 66 bpm, then back down to 60 bpm, and toward the end went up to 68 bpm.'),
  /* 2024-08-27 */
  ('2024-08-27',1,'right index finger',60,61,71,97,98,false,false,'This reading was taken in the morning, in response to a subjective sensation of a high heart rate. I started measuring at 8:27:00 AM, about 30 seconds after putting my finger in, and continued till 8:28:00 AM. The heart rate started at 64-65 bpm in the beginning, fluctuated up to 66 and down to 61, then toward the end it climbed to 71 bpm.'),
  ('2024-08-27',2,'right index finger',120,66,74,96,97,false,false,'This reading was taken in the afternoon, about 2.5 hours after finishing my first meal. I started measuring at 2:50:15 PM, about 40-60 seconds after putting my finger in, and continued till 2:52:15 PM. Within the period I recorded, the heart rate mostly stayed around 70-71 bpm, with occasional fluctuation in the 68-72 bpm range, and one increase to 74 bpm and one drop to 66 bpm. This reading continues to be high relative to my usual, and is indicative that something is going on.'),
  /* 2024-08-28 */
  ('2024-08-28',1,'right index finger',75,50,55,97,100,false,false,'This reading was taken from 9:52:15 AM to 9:53:30 AM, before starting my first meal. I took this reading to assess my recovery from the heart rate spike of the last two days. The heart rate started around 52-55 bpm and later dropped to around 50 bpm before rising back up to around 54 bpm. Overall, my heart rate is now within the normal range, suggesting recovery.'),
  /* 2024-08-29 */
  ('2024-08-29',1,'left index finger',135,46,62,99,100,false,false,'This reading was taken from 8:39:15 AM to 8:41:30 AM with my left index finger, after I initially tried with my right index finger but failed to get a reading. The reading was mostly in the range of 48 bpm to 52 bpm, with occasional fluctuations down to 46 bpm and up to 54 bpm. There was, however, one brief spike up to 62 bpm for a few seconds.'),
  /* 2024-09-02 */
  ('2024-09-02',1,'right index finger',120,44,50,97,100,false,false,'This reading was taken from 10:57:30 AM to 10:59:30 AM. This was over an hour after a bowel movement and before eating or exercise. The reading started out in the 48-50 bpm range with SpO2 around 98-99%; toward the end, the heart rate dropped to the 44-46 bpm range. The SpO2 briefly dropped to 97% and briefly rose to 100% over the interval.'),
  /* 2024-09-06 */
  ('2024-09-06',1,'right index finger',180,48,61,92,99,false,false,'This reading was taken from 9:17:30 AM to 9:20:30 AM. My reading initially started to 50 bpm / 99% SpO2, then dropped to 48 bpm / 99% SpO2 and stayed there for a while. Then, over time, the heart rate rose to arond 55 bpm, and the SpO2 dropped to about 96%. The ehart rate then had two brief spies  to 60 bpm and 61 bpm respectively, returning to the 50-55 bpm range each time. The SpO2 continued to drop to around 93-94%, with a brief dip to 92%.'),
  ('2024-09-06',2,'right index finger',90,74,88,96,98,true,false,'This reading was taken about 3 minutes after sitting down after returning from jogging. The reading was taken over a period of 90 seconds from 10:18:45 AM to 10:20:15 AM. The reading started in the range of 78-85 bpm, and mostly stayed there, with a brief spike up to 88 bpm and a brief drop down to 74 bpm. The SpO2 was around 97% with a brief increase to 98% and a brief drop to 96%.'),
  ('2024-09-06',3,'right index finger',60,58,68,97,99,false,false,'This reading was taken about 1 hour 25 minutes after returning from jogging. The reading was taken over a period of 60 seconds from 11:39:15 AM to 11:40:15 AM. Prior to starting to take the reading, when I first put my finger in the pulse oximeter, the heart rate reading was around 82, but it dropped quickly to 68 bpm and then slowed down; that''s when I started measuring. The heart rate fluctuated in the range of 58 bpm to 68 bpm, mostly staying in the middle. The SpO2 started out around 99% and dropped to 98% and then 97%.'),
  /* 2024-09-10 */
  ('2024-09-10',1,'right index finger',120,58,69,98,98,false,false,'This reading was observed between 3:50:15 PM and 3:52:15 PM, starting about a minute after I put my finger in the pulse oximeter. For the most part, the reading was 58-65 bpm, mostly staying at around 61-64 bpm. Toward the end, there was a brief spike to 69 bpm before returning back down to the 58-65 bpm range. This reading was taken about 2 hours 20 minutes after finishing my last meal, so it isn''t within the two-hour range needed for the boolean column, but close enough to explain the higher reading compared to morning readings.');
